src/Brightside.DevCom.WebUI/Models/FromPhpViewModel.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FromPhpViewModel.cs" company="">
//   
// </copyright>
// <summary>
//   The from php view model.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace Brightside.DevCom.WebUI.Models
{
    /// <summary>
    ///     The from php view model.
    /// </summary>
    public class FromPhpViewModel
    {
        #region Public Properties

        /// <summary>
        ///     Gets or sets the checkbox.
        /// </summary>
        public string Checkbox { get; set; }

        /// <summary>
        ///     Gets or sets the options radio.
        /// </summary>
        public string OptionsRadio { get; set; }

        /// <summary>
        ///     Gets or sets the text box.
        /// </summary>
        public string TextBox { get; set; }

        #endregion
    }
}

src/Brightside.DevCom.WebUI/Models/HomeDetailsViewModel.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="HomeDetailsViewModel.cs" company="">
//   
// </copyright>
// <summary>
//   The home details view model.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace Brightside.DevCom.WebUI.Models
{
    using System;

    /// <summary>
    ///     The home details view model.
    /// </summary>
    public class HomeDetailsViewModel
    {
        #region Public Properties

        /// <summary>
        /// Gets or sets the installation type.
        /// </summary>
        public Type InstallationType { get; set; }

        /// <summary>
        ///     Gets or sets the session test.
        /// </summary>
        public string SessionTest { get; set; }

        #endregion
    }
}

src/Brightside.DevCom.WebUI/Models/NavigationViewModel.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="NavigationViewModel.cs" company="">
//   
// </copyright>
// <summary>
//   The navigation view model.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Brightside.DevCom.WebUI.Models
{
    using Brightside.DevCom.Infrastructure.Web.Plugin.Navigation.Entities;

    /// <summary>
    /// The navigation view model.
    /// </summary>
    public class NavigationViewModel
    {
        #region Public Properties

        /// <summary>
        /// Gets or sets the navigation.
        /// </summary>
        public Navigation Navigation { get; set; }

        #endregion
    }
}

src/Brightside.DevCom.WebUI/Models/ToPHPModel.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ToPHPModel.cs" company="">
//   
// </copyright>
// <summary>
//   The to php model.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace Brightside.DevCom.WebUI.Models
{
    /// <summary>
    ///     The to php model.
    /// </summary>
    public class ToPHPModel
    {
        #region Public Properties

        /// <summary>
        ///     Gets or sets a value indicating whether checkbox.
        /// </summary>
        public bool Checkbox { get; set; }

        /// <summary>
        ///     Gets or sets the radio.
        /// </summary>
        public SessionTest Radio { get; set; }

        /// <summary>
        ///     Gets or sets the textbox.
        /// </summary>
        public string Textbox { get; set; }

        #endregion
    }

    /// <summary>
    ///     The session test.
    /// </summary>
    public enum SessionTest
    {
        /// <summary>
        ///     The option 1.
        /// </summary>
        Option1, 

        /// <summary>
        ///     The option 2.
        /// </summary>
        Option2
    }
}

src/Brightside.DevCom.WebUI/Controllers/HomeController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="HomeController.cs" company="">
//   
// </copyright>
// <summary>
//   The home controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Brightside.DevCom.WebUI.Controllers
{
    using System.Web.Mvc;

    /// <summary>
    /// The home controller.
    /// </summary>
    public class HomeController : Controller
    {
        #region Public Methods and Operators

        /// <summary>
        /// The index.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Index()
        {
            return this.View();
        }

        #endregion
    }
}

src/Brightside.DevCom.WebUI/Controllers/NavigationController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="NavigationController.cs" company="">
//   
// </copyright>
// <summary>
//   The post controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace Brightside.DevCom.WebUI.Controllers
{
    using System.Web.Mvc;

    using Brightside.DevCom.Infrastructure.Web.Plugin.Navigation;
    using Brightside.DevCom.WebUI.Models;

    /// <summary>
    ///     The post controller.
    /// </summary>
    public class NavigationController : Controller
    {
        #region Fields

        /// <summary>
        /// The navigation.
        /// </summary>
        private readonly IProvideNavigationTree navigation;

        #endregion

        #region Constructors and Destructors

        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationController"/> class.
        /// </summary>
        /// <param name="navigation">
        /// The navigation.
        /// </param>
        public NavigationController(IProvideNavigationTree navigation)
        {
            this.navigation = navigation;
        }

        #endregion

        #region Public Methods and Operators

        /// <summary>
        ///     The index.
        /// </summary>
        /// <returns>
        ///     The <see cref="ActionResult" />.
        /// </returns>
        public ActionResult Index()
        {
            return this.PartialView(new NavigationViewModel { Navigation = this.navigation.GetNavigation() });
        }

        #endregion
    }
}

src/Brightside.DevCom.WebUI/Views/Home/Index.cshtml
<section id="posts">
    <div class="page-header">
        <h2>DevCom Examples</h2>
    </div>
    
    <div class="content">
        <div class="list-group">
          <a href="#" class="list-group-item active">
            Knockout
          </a>
          <a href="@Url.Action("Index", "Knockout")" class="list-group-item">Observables</a>
          <a href="@Url.Action("Computed", "Knockout")" class="list-group-item">Computed</a>
          <a href="@Url.Action("Subscriptions", "Knockout")" class="list-group-item">Subscriptions</a>
          <a href="@Url.Action("Index", "Post")" class="list-group-item">Posts</a>
        </div>
    </div>
</section>

src/Brightside.DevCom.WebUI/Views/Navigation/Index.cshtml
@model Brightside.DevCom.WebUI.Models.NavigationViewModel

@this.Html.RenderNavigation(this.Model.Navigation, false)

@{
    using (this.Html.BeginScriptContext())
    {
        this.Html.AddScriptFile("~/js/mylibs/navigation.index.js");
    }

}

src/Brightside.DevCom.WebUI/Views/Shared/Pagination.cshtml
<ul class="pagination pull-right hide" data-bind="visible: data().length > 0, css: { 'hide': data().length == 0 }">
    <li class="prev-container hand" data-bind="css: { disabled: pageNumber() === 1 }, click: function (e) { navigate('prev') }">
        <a class="prev">← Previous</a>
    </li>
    <li class="first-container hand" data-bind="css: { disabled: pageNumber() === 1 }, click: function (e) { navigate('first') }">
        <a class="first">First</a>
    </li>
    <!-- ko foreach: pages -->
    <li class="hand" data-bind="css: { active: $parent.pageNumber() == $data }, click: function (e) { $parent.navigate($data) }">
        <a title="View Page $data">
            <span data-bind="text: $data"></span>
        </a>
    </li>
    <!-- /ko -->
    <li class="last-container hand" data-bind="css: { disabled: pageNumber() === pageCount() }, click: function (e) { navigate('last') }">
        <a class="last">Last</a>
    </li>
    <li class="next-container hand" data-bind="css: { disabled: pageNumber() === pageCount() }, click: function (e) { navigate('next') }">
        <a class="next">Next →</a>
    </li>
</ul>

src/Brightside.DevCom.WebUI/Views/Shared/_Layout.cshtml
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
    <html class="no-js" lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame Remove this if you use the .htaccess -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>@this.Page.Title</title>
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- CSS : implied media="all" -->
    @Styles.Render("~/css/bootstrap")
    @Styles.Render("~/css/fontawesome")
    @Styles.Render("~/css/styles")

    <link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">

    @this.RenderSection("HeadContent", false)
    @Scripts.Render("~/js/modernizr")
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">

        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                @this.Html.ActionLink("Brightside DevCom", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    @{ this.Html.RenderAction("Index", "Navigation"); }
                </ul>
            </div>
        </div>
    </nav>

    <div class="main">
        <div class="container">
            @this.RenderBody()
        </div>
    </div>
    <!--! end of #container -->

    <!-- All JavaScript at the bottom, except for Modernizr and Respond.
        Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
        For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->

    <script src="@this.Url.Content("~/js/libs/require.js")"> </script>
    <script src="@this.Url.Content("~/js/main.js")"> </script>

    @this.Html.RenderScripts(false)

    <script>
        require(['jquery', 'signalr.hubs'], function($) {
            $.connection.hub.start({ waitForPageLoad: false });
        });
    </script>

    <!--[if lt IE 7 ]>
        <script src="@Scripts.Url("~/js/dd_belatedpng")"> </script>
        <script> DD_belatedPNG.fix('img, .png_bg');// Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
    <![endif]-->

    <script type="text/html" id="validation-template">
        <div class="alert alert-danger alert-validation" data-bind="visible: !field.isValid()">
            <span data-bind="validationMessage: field"></span>
        </div>
    </script>
</body>
</html>